name: Build macOS .app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install py2app
        run: pip install py2app

      - name: List installed packages
        run: pip freeze  # Show installed packages

      - name: Build the .app file
        run: |
          python setup.py py2app || cat dist/*.log  # Display logs if the build fails

      - name: Zip the .app file
        run: |
          cd dist
          zip -r app.zip app.app

      - name: Upload the ZIP to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-macos.zip
          path: dist/app.zip
