name: Build macOS .app

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install py2app
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build the .app file
        run: |
          python setup.py py2app

      - name: Zip the .app file
        run: |
          cd dist
          zip -r app.zip app.app

      - name: Upload the ZIP to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: app-macos.zip
          path: dist/app.zip
