name: Build macOS .app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Updated to v4 to use Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5 to use Node.js 20
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install py2app
        run: pip install py2app

      - name: Build the .app file
        run: python setup.py py2app

      - name: Zip the .app file
        run: |
          cd dist
          zip -r app.zip app.app

      - name: Upload the ZIP to GitHub Artifacts
        uses: actions/upload-artifact@v3  # Still on v3 (no Node.js warning for this)
        with:
          name: app-macos.zip
          path: dist/app.zip
